- name: provision ssh keys
  hosts: "all"
  become: yes

  tasks:
    - name: Check if provision user exists for this server
      stat:
        path: /home/provision
      register: folder

    - name: Write ssh authorized keys for provision user
      template:
        src: "../templates/authorized_keys.j2"
        dest: "/home/provision/.ssh/authorized_keys"
        owner: provision
        group: provision
        mode: 0600
      when: folder.stat.exists

    - name: Check if deploy user exists for this server
      stat:
        path: /home/deploy
      register: folder

    - name: Write ssh authorized keys for deploy user
      template:
        src: "../templates/authorized_keys.j2"
        dest: "/home/deploy/.ssh/authorized_keys"
        owner: deploy
        group: deploy
        mode: 0600
      when: folder.stat.exists

#    - name: Check if php is installed
#      shell: "which php"
#      register: is_php_installed
#      failed_when: false
#
#    - name: Add the deb.sury.org trusted key
#      apt_key:
#        id: 95BD4743
#        url: https://packages.sury.org/php/apt.gpg
#      when: is_php_installed.rc == 0
